language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
services:
    - rabbitmq
    - redis-server
    - memcached
install:
    - composer install
script:
    - php vendor/bin/phing
notifications:
    email: false
cache:
    directories:
        - $HOME/.composer/cache
        - vendor/
